name: journal
description: A simple journaling app.

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+16"
  intl: "^0.15.6"
  path: "^1.5.1"
  path_provider: "^0.4.0"
  uuid: "^1.0.0"
  yaml: "^2.1.13"

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
