name: journal
description: A Journaling App Built on top of Git
version: 1.0.0+2

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.6"
  path: "^1.5.1"
  uuid: "^1.0.0"
  yaml: "^2.1.13"
  firebase_analytics: ^1.1.0
  flutter_crashlytics: ^0.2.0
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.3
  dots_indicator: ^0.0.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
