name: journal
description: A simple journaling app.

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+16"
  intl: "^0.15.6"
  path: "^1.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
