name: journal
description: A Journaling App Built on top of Git

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.6"
  path: "^1.5.1"
  uuid: "^1.0.0"
  yaml: "^2.1.13"
  firebase_analytics: ^1.1.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
