name: gitjournal
description: A Journaling App Built on top of Git
version: 1.1.14+10

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.6"
  path: ^1.6.2
  uuid: ^2.0.1
  yaml: ^2.2.0
  firebase_analytics: ^4.0.2
  flutter_crashlytics: ^1.0.0
  shared_preferences: ^0.5.2
  url_launcher: ^5.0.2
  dots_indicator: ^0.0.3
  package_info: ^0.4.0+3
  http: ^0.12.0+1
  badges: ^0.0.6
  share: ^0.6.1+1
  launch_review: ^2.0.0
  device_info: ^0.4.0+1
  flutter_markdown: ^0.2.0
  flutter_email_sender: ^2.0.3
  function_types: ^0.0.2
  auto_size_text: ^2.0.1
  fimber: ^0.3.0
  preferences: ^4.0.0
  dynamic_theme: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/icon.png"
    - "assets/icon/github-icon.png"
    - "assets/icon/gitlab-icon.png"
    - "assets/OnBoardingMarkdown.png"
    - "assets/OnBoardingGitProviders.png"
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  ios: true
