version: 2
jobs:
  build:
    docker:
      - image: vhanda/flutter-android:latest
    steps:
      - checkout
      - run:
          name: Get NDK Libraries
          command: apt-get update && apt-get install -y jq && ./scripts/download_ndk_libs.sh
      - run:
          name: Test
          command: flutter test
      - run:
          name: Analyze
          command: flutter analyze
      - run:
          name: Decode Android key store
          command: echo "$KEYSTORE" | base64 -di > android/app/keystore.jks
      - run:
          name: Create Google Play key
          command: echo "$GOOGLE_PLAY_KEY" | base64 -di > android/google-play-api-key.json
      - run:
          name: Create Android Key file
          command: echo "$ANDROID_KEY_FILE" | base64 -di > android/key.properties
      - run:
          name: Build
          command: ./scripts/build.sh
      - store_artifacts:
          path: build/app/outputs/bundle/release/app.aab
          destination: gitjournal.aab
      - run:
          name: Upload Crashlytics Symbols
          command: ./scripts/android_crashlytics.sh
      - run:
          name: Publish Beta
          command: cd android && fastlane betaBuild
