version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Test
          command: flutter test
      - run:
          name: Analyze
          command: flutter analyze
      - run:
          name: Decode Android key store
          command: echo "$KEYSTORE" | base64 -di > android/app/keystore.jks
      - run:
          name: Create Google Play key
          command: echo "$GOOGLE_PLAY_KEY" | base64 -di > android/google-play-key.json
      - run:
          name: Create Android Key file
          command: echo "$ANDROID_KEY_FILE" | base64 -di > android/key.properties
      - run:
          name: Accept Android Licenses
          command: $ANDROID_HOME/tools/bin/sdkmanager --update
      - run:
          name: Publish Beta
          command: cd android && fastlane betaBuild
