version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Test
          command: flutter test
      - run:
          name: Analyze
          command: flutter analyze
