name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.2"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign
