name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.3"
      - run: flutter pub get
      - run: which dart
      - run: dart ./scripts/setup_env.dart
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      #- run: flutter test
      - run: ./scripts/build_ios.sh
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
